### ISSUE TITLE
Blocking t.stripe.com breaks all of invoicing

### ISSUE THREAD

**Issue by devtimi** [shreyasminocha/shady-hosts#14]
Blocking `t.stripe.com` breaks all of invoicing, no invoice will load. I interested in what specifically `t.stripe.com` does that outweighs the whole invoicing feature? I have whitelisted it locally, but was curious what kind of tracking is used that I should perhaps be wary of.

Thanks!

**Comment by shreyasminocha** [comment]
Thanks for reporting this @devtimi. It may be that this is a false-positive. I'll go ahead and unblock it for now.
