### ISSUE TITLE
`tms.fmm.io`

### ISSUE THREAD

**Issue by shreyasminocha** [shreyasminocha/shady-hosts#2]
www.rfi.fr makes a request to https://tms.fmm.io/rfi/en.js.

**Comment by romainst** [comment]
This file is hosted on a domain owned and operated by France Médias Monde (fmm.io), parent company of RFI. It ensures GDPR (legal) compliance and should NOT be blocked.

**Comment by shreyasminocha** [comment]
Checks out, but it seems EasyPrivacy—which is generally trustworthy—[now contains](https://github.com/easylist/easylist/commit/082b378cdfd778c9e8ad3b37e75ccc20069b17e7) a `||tms.fmm.io^` rule. Perhaps the `tms` subdomain does tracking-related things? In any case, since this domain is on EasyPrivacy's radar now I guess this issue is obsolete.
