### ISSUE TITLE
Blocklist issue: improving.duckduckgo.com

### ISSUE THREAD

**Issue by danieldurrans** [shreyasminocha/shady-hosts#8]
Blocking of improving.duckduckgo.com has started to negatively impact the use of duckduckgo.com

Consequence:
- Search results page not fully loading
- Duckduckgo functionally not working

Explicitly whitelisting this domain resolved useability issues with duckduckgo.

This issue was noticed when using a default pihole configuration, pulling a blocklist from https://github.com/StevenBlack/hosts

**Comment by shreyasminocha** [comment]
Resolved in 1ebef665a6afc16a43bbee82895921620fcaefa7.
