### ISSUE TITLE
graph.microsoft.com

### ISSUE THREAD

**Issue by TPS** [shreyasminocha/shady-hosts#9]
Per https://docs.microsoft.com/en-us/graph/overview-major-services, `graph.microsoft.com` deserves some consideration for blocking, but am concerned about problems like https://github.com/StevenBlack/hosts/issues/1853.  What do y'all think?

Originally filed @ https://github.com/StevenBlack/hosts/issues/1864.

**Comment by shreyasminocha** [comment]
Yeah I'm also afraid blocking this will break things. While it could be used for tracking and analytics, there seem to be plenty of [legitimate uses of Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview#popular-api-requests). Unless I'm mistaken, I think we'll pass on this one.
